### ISSUE TITLE
test_stack failed on POWER7

### ISSUE THREAD

**Issue by ivmai** [ivmai/libatomic_ops#15]
RHELinux6/POWER7 (gcc-4.4.7-3/ppc64), Fedora16/POWER7 (gcc-4.6.2-1/ppc64),
Debian/powerpc (gcc 4.6.3-7):
test_stack failed (Debian Bug #680100).

Bug reported by Will Schmidt will_schmidt@vnet.ibm.com (Feb 1, 2014)

**Comment by ffabbri4** [comment]
I can easily reproduce the problem also with xlC compiler, following Debian Bug #680100 and try to apply that workaround look that does not solve the problem.

**Comment by ivmai** [comment]
Related links:
* https://lists.opendylan.org/pipermail/bdwgc/2012-November/005431.html
* https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/c4k8ZrmQrEI
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=680100#15

**Comment by ivmai** [comment]
Recent links:
* https://lists.opendylan.org/pipermail/bdwgc/2016-July/006184.html
* https://lists.opendylan.org/pipermail/bdwgc/2016-July/006185.html
* https://lists.opendylan.org/pipermail/bdwgc/2016-July/006186.html

**Comment by ivmai** [comment]
Fix committed -  85dd735
Testing on PowerPC is needed

**Comment by hboehm** [comment]
Looks good to me.  Let's see if the test results agree.

**Comment by ivmai** [comment]
Will Schmidt says the patch does not help (on power7 and power8)

**Comment by hboehm** [comment]
I will stare at it some more.

**Comment by trex58** [comment]
Hello
We are BullFreeware team (port of OpenSource Software on AIX). Now porting GC 7.6.0 .
libatomic_ops 7.4.4 is included inside GC .
We have a patch for an issue. But it does not seem related to the test_stack test failure.
We can reproduce the test_stack failure here. We'll have a look at it asap.

**Comment by trex58** [comment]
Hi, I'm having strange behavior with test_stack test. When launching it several times, by a line like:
.libs/lt-test_stack 4 ; .libs/lt-test_stack 4 ;  .libs/lt-test_stack 4 ; .libs/lt-test_stack 4 ; ...
the first test succeeds and many of the following tests fail.
However, when adding a "sleep 1" between each test, ALL tests succeed.
It looks like there is some global data which is cleaned just after the process has terminated. However, it seems to requires some tenths of a second for this cleaning to be done.

**Comment by mattst88** [comment]
Confirmed. Still broken on master.

**Comment by ivmai** [comment]
> Confirmed. Still broken on master.
If so, I have reverted "Fix store-load ordering in AO_stack_pop_explicit_aux_acquire".
At this moment, we do not know how to fix it.

**Comment by ivmai** [comment]
Discussion is continued in #24

**Comment by ivmai** [comment]
To @mattst88, @trex58: Could you please test master of https://github.com/ffabbri4/libatomic_ops on Power 7/8  target? (both with and without configure --disable-atomic-intrinsics option)

**Comment by ivmai** [comment]
The test failure should be fixed by 7ce7da4

**Comment by mattst88** [comment]
Thanks. I confirm that everything is passing with and without --disable-atomic-intrinsics.
