### ISSUE TITLE
Release request for mips64el support

### ISSUE THREAD

**Issue by ianw** [ivmai/libatomic_ops#20]
Hi,

I recently updated Debian package to 7.4.4 and must have misread the history, because I thought that all the mips64el patches were in that branch, but I guess not so

From the bug report [1] you can see I missed

* Remove 0001-Use-LLD-and-SCD-instructions-on-mips64.patch (54d1da56809b892d2fc521fea0fd41ea8c23e4f2)
* Remove 004-Support-n32-ABI-for-mips64.patch (d3e884b41ede6d5a83ec480f72a8ed6fb4984e3c)

I'd much prefer to just be in sync with upstream than carry patches in the package.  Do you think we could get these into a 7.4.5 release which I could update the package to?

Thanks,

-i

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773205

**Comment by ivmai** [comment]
I see. I will add these patches to release-7_4 branch in several days.
I estimate to have a release this year.

**Comment by ivmai** [comment]
I have added mips64 support to [release-7_4](https://github.com/ivmai/libatomic_ops/tree/release-7_4) branch. Please test it.
