### ISSUE TITLE
Option to omit documentation at install

### ISSUE THREAD

**Issue by ivmai** [ivmai/libatomic_ops#28]
Reported by @concatime (#27) : could you provide an option to install only shared libraries like [here](https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md#advanced-compilation), it would be really useful for a lot of us.

**Comment by ivmai** [comment]
To @concatime: Could you please be more verbose: which configure option(s) do you need? you need to omit .h and doc files installation, right?

**Comment by concatime** [comment]
Well, for my [script}(//gist.github.com/concatime/36d58b967c7ef7f66e7acee91aea973c) which install nginx and components,  When It's time to install libatomic_ops, I need headers (with the pkgconfig) and shared libraries since nginx use your awesome library. Like you see it [here](//gist.github.com/concatime/36d58b967c7ef7f66e7acee91aea973c#file-sh-L35), it's a lot easier than manually copying file like [here](//gist.github.com/concatime/36d58b967c7ef7f66e7acee91aea973c#file-sh-L53). Think about it, do I really need docs if I'm only using it as a part of something else ;)

**Comment by ivmai** [comment]
Ok, I will add "--disable-docs" to configure.

**Comment by concatime** [comment]
Awesome!

**Comment by ivmai** [comment]
Now it should work for you. Please test.

**Comment by concatime** [comment]
I'm lost. There is no `configure` file.

**Comment by concatime** [comment]
Well, looking into Travis, I was able to reproduce the steps. So, it seems to work perfectly.
The only thing that I would modify (and it's up to you), is the symlink:
```
libatomic_ops.so -> libatomic_ops.so.1.1.1
libatomic_ops.so.1 -> libatomic_ops.so.1.1.1
```
It would be better for reading of it was like this: `libatomic_ops.so -> libatomic_ops.so.1`, for a global result:
`libatomic_ops.so -> libatomic_ops.so.1 -> libatomic_ops.so.1.1.1` (for libatomic_ops_gpl also).

**Comment by concatime** [comment]
> Thus, /usr/lib/libreadline.so.3 is a fully-qualified soname, which ldconfig would set to be a symbolic link to some realname like /usr/lib/libreadline.so.3.0. There should also be a linker name, /usr/lib/libreadline.so which could be a symbolic link referring to /usr/lib/libreadline.so.3.
[Source](//tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html).

**Comment by concatime** [comment]
Then, if the name change to `libatomic_ops.so.1.1.2` for example, you would then modify only `ibatomic_ops.so.1`, and not `ibatomic_ops.so`.

**Comment by ivmai** [comment]
> It would be better for reading of it was like this: libatomic_ops.so -> libatomic_ops.so.1

I agree. But I think this is the behavior of libtool.

**Comment by concatime** [comment]
Oh, ok, not a real issue. I'm waiting for a release to add `--disable-docs` into my script. Thank you.

**Comment by ivmai** [comment]
7.6.2 is released (https://github.com/ivmai/libatomic_ops/releases/tag/v7.6.2)
