### ISSUE TITLE
Status of 7.6.0?

### ISSUE THREAD

**Issue by ilovezfs** [ivmai/libatomic_ops#29]
7.6.0 is over 8 months old now. Is it still considered pre-release?

**Comment by ivmai** [comment]
Libatomic_ops 7.6.0 was released 3 months ago. A number of minor non-significant issues have been discovered and fixed since the release. So, it actually OK to use in production.
I plan to make 7.6.2 release in November.

**Comment by ilovezfs** [comment]
Cool. Which version would you like to be in Homebrew's stable spec?

**Comment by ivmai** [comment]
I think the proper and formal decision is to use stable version (7.4.6 as of now) for the stable spec.
If you have an experimental spec, use 7.6.0 for it.

**Comment by ilovezfs** [comment]
thanks!

**Comment by concatime** [comment]
November, here we are ;) Some updates?

**Comment by ivmai** [comment]
A couple of weeks. I will release it along with bdwgc, several issues are to be fixed before the release.

**Comment by ivmai** [comment]
7.6.2 is released (https://github.com/ivmai/libatomic_ops/releases/tag/v7.6.2)

**Comment by ilovezfs** [comment]
Thanks @ivmai! Voilà: https://github.com/Homebrew/homebrew-core/pull/22092

**Comment by ivmai** [comment]
BTW. You could also update bdwgc to v7.6.2 (homebrew-core/Formula/bdw-gc.rb)

**Comment by ilovezfs** [comment]
@ivmai :tada: https://github.com/Homebrew/homebrew-core/pull/22113

The tarball is missing in http://www.hboehm.info/gc/gc_source/

**Comment by ivmai** [comment]
link to recent gc: https://github.com/ivmai/bdwgc/releases/download/v7.6.2/gc-7.6.2.tar.gz

**Comment by ilovezfs** [comment]
@ivmai yup that's what I used in https://github.com/Homebrew/homebrew-core/pull/22113

**Comment by ilovezfs** [comment]
@ivmai given the upgrade on bdwgc is 7.6.0 -> 7.6.2 was the library version intentionally changed in a linkage breaking way? I'm going to need to rebuild 14 other packages ... :)

**Comment by ivmai** [comment]
>  given the upgrade on bdwgc is 7.6.0 -> 7.6.2 was the library version intentionally changed in a linkage breaking way?

Yes, see the rationale in https://github.com/ivmai/bdwgc/commit/5f740784f

**Comment by ilovezfs** [comment]
@ivmai OK thanks. In terms of semver, it's slightly odd for that to happen with only a change in the patch-level version number … but I will start rebuilding the packages :)

**Comment by ivmai** [comment]
The API incompatible change (https://github.com/ivmai/bdwgc/commit/2dd4ee71d) happened in 7.2alpha1 but I've noticed that the version-info is not updated only recently. I'm sorry about it.

**Comment by ilovezfs** [comment]
@ivmai no worries. That's actually good news since it means we shouldn't expect any of the rebuilds to fail.

**Comment by ilovezfs** [comment]
@ivmai I do wonder if it's really worth changing the version now. 7.2 has been the released version for over 5 years now and only Debian wheezy (oldoldstable) is still on a version less than < 7.2 https://packages.debian.org/wheezy/libgc-dev

**Comment by ivmai** [comment]
> I do wonder if it's really worth changing the version now.

It's late to ask this question, the version is already changed and 7.6.2 is released.

**Comment by ilovezfs** [comment]
OK.

**Comment by ilovezfs** [comment]
@ivmai I have now shipped 7.6.2 in Homebrew.
