### ISSUE TITLE
Test suite fails to build with gcc-7 on amd64

### ISSUE THREAD

**Issue by mattst88** [ivmai/libatomic_ops#34]
See downstream bugs https://bugs.gentoo.org/638222 and https://bugs.gentoo.org/641410

libatomic_ops fails to build its test suite on amd64 with gcc-7, where it successfully built with gcc-6.4.0. We've seen undefined references to __atomic_compare_exchange_16, _atomic_load_16, and __atomic_store_16.

**Comment by ivmai** [comment]
Confirmed on Ubuntu, thank you for reporting.

Host: Ubuntu 14.04/x64
Compiler: gcc-7.2.0/x64
How to reproduce: ./configure && make check CFLAGS_EXTRA="-march=native"

Quick fix for clients: add -latomic to compiler flags, e.g.: make check CFLAGS_EXTRA="-march=native -latomic"

**Comment by ivmai** [comment]
Fixed by commit 759fa97
The relevant build on Travis CI: https://travis-ci.org/ivmai/libatomic_ops/jobs/359606071

**Comment by ivmai** [comment]
Released in [v7.6.6](https://github.com/ivmai/libatomic_ops/releases/tag/v7.6.6)
