### ISSUE TITLE
How can I get libatomic_ops.a ?

### ISSUE THREAD

**Issue by edoger** [ivmai/libatomic_ops#35]
In Centos 7.4, when compiling nginx with the --with-libatomic=/usr/local/src/libatomic_ops-7.6.4 option, it is reported that libatomic_ops.a does not exist.

**Comment by ivmai** [comment]
After configure && make (in libatomic_ops folder), the file should be in ./src/.libs

**Comment by edoger** [comment]
@ivmai Thanks, NGINX looks for this file in the ./src directory and I report this issue to the NGINX team.

**Comment by ivmai** [comment]
The location was changed in v7.4.0 (released in 2013).

> I report this issue to the NGINX team.

Good.
