### ISSUE TITLE
coredump with '__atomic_fetch_add' function on aarch64 

### ISSUE THREAD

**Issue by H-kernel** [ivmai/libatomic_ops#40]
nginx run on aarch64 ,core dump,gcc 7.3.0:
AO_INLINE AO_t
AO_fetch_and_add(volatile AO_t *addr, AO_t incr)
{
  return __atomic_fetch_add(addr, incr, __ATOMIC_RELAXED);
}

**Comment by ivmai** [comment]
How to reproduce? (Seems to be an issue of gcc, not of libatomic_ops.)

**Comment by H-kernel** [comment]
I fix it,thanks
https://community.arm.com/developer/ip-products/processors/f/cortex-a-forum/5832/what-is-real-application-of-exclusive-access-in-axi/19404#19404
