### ISSUE TITLE
Incorrect use of sizeof operator to verify alignment

### ISSUE THREAD

**Issue by glaubitz** [ivmai/libatomic_ops#48]
```libatomic_ops``` incorrectly uses the ```sizeof``` operator to verify the correct alignment of an address.

For example, in https://github.com/ivmai/libatomic_ops/blob/master/src/atomic_ops/sysdeps/loadstore/atomic_load.h#L31, we have:

```C
    assert(((size_t)addr & (sizeof(*addr) - 1)) == 0);
```

This will work only on architectures where the natural alignment is 32 bits or higher, but will fail on architectures like m68k where the natural alignment is 16 bits:

```bash
root@pacman:~# debfoster
debfoster: /usr/include/atomic_ops/sysdeps/loadstore/atomic_load.h:31: AO_load: Assertion `((size_t)addr & (sizeof(*addr) - 1)) == 0' failed.
Aborted
root@pacman:~#
```

See this discussion: https://lists.debian.org/debian-68k/2020/09/msg00046.html

The proper operator to use would be ```__alignof__``` or ```alignof``` (the later requires C11).

**Comment by ivmai** [comment]
This issue causes https://github.com/ivmai/bdwgc/issues/329

**Comment by ivmai** [comment]
This should be fixed in atomic_load.template and atomic_store.template

**Comment by ivmai** [comment]
> The proper operator to use would be __alignof__

Yes, thank you. But we need to be careful not to break compilation for other and older compilers.

**Comment by ivmai** [comment]
In addition to the W/A above, I've replaced `sizeof` with `__alignof__` in the assertions if C11 - commit 81242ce88799475379f759136b857320e2210476.
