### ISSUE TITLE
Downstream libatomic_ops releases (Sep 2021)

### ISSUE THREAD

**Issue by ivmai** [ivmai/libatomic_ops#49]
Just convenient place to keep record of pushing latest releases downstream.

* https://github.com/ivmai/libatomic_ops/releases/download/v7.6.12/libatomic_ops-7.6.12.tar.gz
file_size: 506313
md5: 0b0b88da4bde5dd770daea3146e78359 
sha1: 8d4c69e8b2ed098ce4e056170fd96fc590c2b885
sha256: f0ab566e25fce08b560e1feab6a3db01db4a38e5bc687804334ef3920c549f3e
sha512: bbf98a38a80c8fe6b7eab773967edc55b8d48be32b36ed827fb835ee3dcd96d5ec1dc97149714e015e93a0a5b9fc03595797663fdb5a0f673869ea8bfe640df5
cksum (linux): 3123545103

[1] https://repology.org/project/libatomic-ops/packages

**Comment by ivmai** [comment]
Cygwin - https://github.com/andyli/libatomic_ops-cygwin/pull/6 (v7.6.12)

**Comment by ivmai** [comment]
Online sha512 generator - https://hash.online-convert.com/sha512-generator

**Comment by ivmai** [comment]
Alpine Linux Edge - in progress
upstream: https://gitlab.alpinelinux.org/alpine/aports
file URL: https://git.alpinelinux.org/aports/plain/main/libatomic_ops/APKBUILD
my fork: https://github.com/ivmai/alpinelinux-aports

**Comment by ivmai** [comment]
AOSC - https://github.com/AOSC-Dev/aosc-os-abbs/pull/3504

**Comment by ivmai** [comment]
ConanCenter - https://github.com/conan-io/conan-center-index/pull/7517

**Comment by ivmai** [comment]
HaikuPorts - https://github.com/haikuports/haikuports/pull/6230

**Comment by ivmai** [comment]
GoboLinux - https://github.com/gobolinux/Recipes/pull/147

**Comment by ivmai** [comment]
MacPorts - https://github.com/macports/macports-ports/pull/12471

Command to create archive: git archive --format=tar.gz --prefix=ivmai-libatomic_ops-`git show-ref --hash=7 v7.6.12`/ -o libatomic_ops-7.6.12.tar.gz v7.6.12

rpmd160 online generator: https://hash.online-convert.com/ripemd160-generator

**Comment by ivmai** [comment]
MidnightBSD mports - https://github.com/MidnightBSD/mports/pull/4 (v7.4.16)

SHA256 (libatomic_ops-7.4.16.tar.gz) = 9e74d145e030dcb69dd580627413acea272d9805dd91724407335685c86c8210
SIZE (libatomic_ops-7.4.16.tar.gz) = 484922

**Comment by ivmai** [comment]
MSYS2 mingw - https://github.com/msys2/MINGW-packages/pull/9711

**Comment by ivmai** [comment]
sagemath - https://github.com/ivmai/sagemath-sage/commit/094a4073b9baff8c275a3965ecf956e2319c5bb7 - incomplete (PRs should be submitted as explained in https://doc.sagemath.org/html/en/developer/manual_git.html)

**Comment by ivmai** [comment]
Adelie Linux: https://git.adelielinux.org/adelie/packages/-/merge_requests/624

**Comment by ivmai** [comment]
Pisi Linux - https://github.com/pisilinux/core/pull/1286

**Comment by ivmai** [comment]
Spack - https://github.com/spack/spack/pull/26512

**Comment by ivmai** [comment]
Void Linux - https://github.com/void-linux/void-packages/pull/33326

**Comment by ivmai** [comment]
Alpine Linux - https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/26139

**Comment by ivmai** [comment]
openEuler: fix typo in spec (v7.6.10) - https://gitee.com/src-openeuler/libatomic_ops/pulls/5
When merged: create a PR to update to v7.6.12

**Comment by ivmai** [comment]
Ataraxia Linux: https://gitlab.com/ataraxialinux/ataraxia/-/merge_requests/1

**Comment by ivmai** [comment]
Sabotage linux: https://github.com/sabotage-linux/sabotage/pull/702

**Comment by rofl0r** [comment]
is there a specific reason you want this new version available in all distros ?

**Comment by ivmai** [comment]
> is there a specific reason you want this new version available in all distros ?

Hello @rofl0r,
Some bugs were fixed since previous release (e.g. as of Sabotage the change between v7.4.2 and v7.4.16 contains fixes in asm code for m68k, aarch64, mips64 and i686). Ideally downstream package maintainers to make the updates but to my understanding it's not obvious for the maintainers what was changed in the upstream and how to update the downstream build scripts or patches correctly. Sometimes the maintainers are not aware that particular bugs were discovered and fixed upstream.
So, my role here, as I see, is to reduce the difficulties in updating the distro packages by participating in the process if possible.

**Comment by ivmai** [comment]
Cygwinports mingw64-x86_64: https://github.com/cygwinports/mingw64-x86_64-libatomic_ops/pull/2

**Comment by ivmai** [comment]
vcpkg: https://github.com/microsoft/vcpkg/pull/21285 (v7.7.0-20211109)
