### ISSUE TITLE
Outdated config.guess Files

### ISSUE THREAD

**Issue by yining765** [ivmai/libatomic_ops#54]
When I was building the package for the `riscv64` platform, the `./configure` step reported `./config.guess: unable to guess system type`. When I updated the relevant files with `autoreconf -fi`, the build was successful. So `config.guess` and `config.sub` in this project need to be updated to work with more architectures.

**Comment by ivmai** [comment]
The release (7.6.14) is prepared by https://app.travis-ci.com/github/ivmai/libatomic_ops/jobs/580857221:
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.15
m4 (GNU M4) 1.4.18
libtool (GNU libtool) 2.4.6

**Comment by ivmai** [comment]
Which autotools versions fit your needs?

BTW master branch has same as above but automake is 1.16.5

**Comment by ivmai** [comment]
Autoconf (2.69-11.1) on Ubuntu 21 has support of riscv64 - https://launchpad.net/ubuntu/focal/+source/autoconf

I think the issue has been already solved in master (by https://github.com/ivmai/libatomic_ops/commit/5bb694c2618c88752fb13c6b0c15715b9ca487d9).
The upcoming release (7.8.2) will have the support of riscv64 in config.guess.
